Kitap Alım İşlemi
archis-academy/Java-Feb-1-Batch pull request #10
Opened 2024-03-22 13:19 UTC by Nehir0109

2024-03-22 15:36 UTC, JamshidS requested changes

2024-03-22 15:36 UTC, JamshidS commented on src/LibraryManagementSystemApplication.java
> +                transactions[quantity][3] = formattedTime;
array out of bounds

2024-03-22 15:36 UTC, JamshidS commented on src/LibraryManagementSystemApplication.java
> +                LocalTime currentTime = LocalTime.now();
you can remove time from here we don't need it anymore

2024-03-22 15:36 UTC, JamshidS commented on src/LibraryManagementSystemApplication.java
> +                quantity++;
create a new variable name it as `transactionQuantity` and use it accordingly

2024-03-22 15:45 UTC, JamshidS commented on src/LibraryManagementSystemApplication.java
> +                transactions[quantity][3] = formattedTime;
example commit format:->  `[JA-04] - commit message`

2024-03-27 15:23 UTC, JamshidS requested changes

2024-03-27 15:23 UTC, JamshidS commented on src/LibraryManagementSystemApplication.java
> +        boolean isFound= false;
String response = "HATA: Kütüphanede kitap bulunamamaktadır!";

2024-03-27 15:23 UTC, JamshidS commented on src/LibraryManagementSystemApplication.java
> +            return "Kitap ödünç alındı. İyi okumalar!";
response = "Kitap ödünç alındı. İyi okumalar!";

2024-03-27 15:23 UTC, JamshidS commented on src/LibraryManagementSystemApplication.java
> +        }else{
return response;

2024-03-27 15:39 UTC, JamshidS approved these changes

2024-03-27 15:39 UTC, merged

2024-04-17 12:21 UTC, Orujhimaru commented
Kodunda bu kisimda - 
  " transactions[quantity][0] = bookISBN;
                transactions[quantity][1] = identityNumber;
                transactions[quantity][2] = formattedDate;
                transactionQuantity++; " 

                quantity'yi index olarak kullaniyorsun. transactionQuantity kullanmamiz gerekmez mi ? , Mesela 4 kitap ekledik, quantity 4, amma daha hicbir kitap daha checkout edilmedigi icin 4-cu indexe degil, birinci indexe koymamiz gerekir.