[JA-23]-kitap iade tarihi kontrolu metot kodları
archis-academy/Java-Feb-1-Batch pull request #11
Opened 2024-03-23 12:34 UTC by yncrahmet

2024-03-23 12:36 UTC, yncrahmet commented on src/LibraryManagementSystemApplication.java
> +        return foundIndex;
I forgot to add the last return statement.

2024-03-27 15:09 UTC, JamshidS requested changes

2024-03-27 15:09 UTC, JamshidS commented on src/LibraryManagementSystemApplication.java
> +    static boolean checkBookReturnDeadline(String patronName){
```suggestion
    static boolean checkBookReturnDeadline(String patronId){
```

2024-03-27 15:09 UTC, JamshidS commented on src/LibraryManagementSystemApplication.java
> +            if (transaction[1].equalsIgnoreCase(patronName)) {
```suggestion
            if (transaction[1].equalsIgnoreCase(patronId)) {
```

2024-03-28 11:34 UTC, yncrahmet reviewed
[JA-23]book return date control method codes update

2024-03-29 15:50 UTC, JamshidS approved these changes

2024-03-29 15:50 UTC, merged